"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useState } from "react";
import { Bell, Boxes, Command, LayoutDashboard, LogOut, Moon, Settings2, Sun, X } from "lucide-react";
import { useTheme } from "next-themes";
import { authClient } from "@/lib/auth/client";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";

const navigation = [{ href: "/dashboard", label: "Overview", icon: LayoutDashboard }, { href: "/onboarding", label: "Workspace setup", icon: Settings2 }];

export function ApplicationShell({ children, user, organizationName }: { children: React.ReactNode; user: { name: string; email: string }; organizationName?: string }) {
  const pathname = usePathname(); const router = useRouter(); const { resolvedTheme, setTheme } = useTheme(); const [notificationsOpen, setNotificationsOpen] = useState(false); const [commandOpen, setCommandOpen] = useState(false);
  const signOut = async () => { await authClient.signOut(); router.replace("/sign-in"); router.refresh(); };
  return <div className="min-h-screen bg-[var(--background)]">
    <aside className="fixed inset-y-0 left-0 z-30 hidden w-64 border-r bg-[var(--surface-solid)] p-4 lg:flex lg:flex-col">
      <Link href="/dashboard" className="flex items-center gap-2.5 px-2 py-2 text-sm font-black tracking-[-.04em]"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[var(--brand)] text-white shadow-lg shadow-indigo-500/20"><Boxes size={17} /></span><span>BUSINESS OS</span></Link>
      <div className="mt-8 px-2"><p className="truncate text-xs font-semibold uppercase tracking-[.12em] text-[var(--muted)]">{organizationName ?? "Your workspace"}</p></div>
      <nav className="mt-3 space-y-1" aria-label="Primary navigation">{navigation.map((item) => { const Icon = item.icon; const active = pathname === item.href; return <Link key={item.href} href={item.href} className={cn("focus-ring flex h-10 items-center gap-3 rounded-xl px-3 text-sm font-semibold transition-colors", active ? "bg-indigo-500/10 text-[var(--brand)]" : "text-[var(--muted)] hover:bg-[var(--muted-surface)] hover:text-[var(--foreground)]")}><Icon size={18} strokeWidth={active ? 2.4 : 2} />{item.label}</Link>; })}</nav>
      <div className="mt-auto rounded-xl border bg-[var(--muted-surface)]/50 p-3"><p className="truncate text-sm font-bold">{user.name}</p><p className="mt-0.5 truncate text-xs text-[var(--muted)]">{user.email}</p><button onClick={signOut} className="focus-ring mt-3 flex items-center gap-2 text-xs font-bold text-[var(--muted)] hover:text-[var(--danger)]"><LogOut size={14} />Sign out</button></div>
    </aside>
    <div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b bg-[var(--background)]/82 px-5 backdrop-blur-xl sm:px-8"><div className="flex items-center gap-3"><Link href="/dashboard" className="flex items-center gap-2 text-sm font-black lg:hidden"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[var(--brand)] text-white"><Boxes size={15} /></span>BOOS</Link><button onClick={() => setCommandOpen(true)} className="focus-ring hidden h-9 w-64 items-center justify-between rounded-lg border bg-[var(--surface-solid)] px-3 text-xs text-[var(--muted)] sm:flex"><span className="flex items-center gap-2"><Command size={14} />Quick navigation</span><kbd className="rounded border bg-[var(--muted-surface)] px-1.5 py-0.5 text-[10px]">⌘ K</kbd></button></div><div className="flex items-center gap-1"><button onClick={() => setTheme(resolvedTheme === "dark" ? "light" : "dark")} className="focus-ring grid h-9 w-9 place-items-center rounded-lg text-[var(--muted)] hover:bg-[var(--muted-surface)] hover:text-[var(--foreground)]" aria-label="Toggle color theme">{resolvedTheme === "dark" ? <Sun size={18} /> : <Moon size={18} />}</button><button onClick={() => setNotificationsOpen(!notificationsOpen)} className="focus-ring relative grid h-9 w-9 place-items-center rounded-lg text-[var(--muted)] hover:bg-[var(--muted-surface)] hover:text-[var(--foreground)]" aria-label="Toggle notifications"><Bell size={18} /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-[var(--brand)]" /></button></div></header>
      <main className="mx-auto max-w-[1600px] px-5 py-6 sm:px-8 sm:py-8">{children}</main>
    </div>
    {notificationsOpen && <aside className="surface fixed inset-y-0 right-0 z-40 w-full max-w-sm p-5 shadow-2xl" aria-label="Notifications"><div className="flex items-center justify-between"><div><p className="text-sm font-black">Notifications</p><p className="mt-1 text-xs text-[var(--muted)]">Your operational alerts appear here.</p></div><button onClick={() => setNotificationsOpen(false)} className="focus-ring grid h-8 w-8 place-items-center rounded-lg hover:bg-[var(--muted-surface)]" aria-label="Close notifications"><X size={18} /></button></div><div className="mt-10 rounded-xl border border-dashed p-8 text-center"><Bell className="mx-auto text-[var(--muted)]" size={24} /><p className="mt-3 text-sm font-bold">You’re all caught up</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">Low stock, payment-due and workflow alerts will be delivered here.</p></div></aside>}
    {commandOpen && <div className="fixed inset-0 z-50 grid place-items-start bg-slate-950/35 px-4 pt-[18vh] backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Quick navigation" onMouseDown={() => setCommandOpen(false)}><div className="surface w-full max-w-lg overflow-hidden rounded-2xl" onMouseDown={(event) => event.stopPropagation()}><div className="flex items-center gap-2 border-b px-4"><Command size={17} className="text-[var(--muted)]" /><input autoFocus placeholder="Jump to…" className="h-12 min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[var(--muted)]" /></div><div className="p-2">{navigation.map((item) => { const Icon = item.icon; return <Link key={item.href} href={item.href} onClick={() => setCommandOpen(false)} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold hover:bg-[var(--muted-surface)]"><Icon size={17} />{item.label}</Link>; })}</div></div></div>}
  </div>;
}
