import { redirect } from "next/navigation";
import { ArrowDownRight, ArrowUpRight, Boxes, CreditCard, IndianRupee, PackageSearch, ReceiptText, ShoppingBag, TrendingUp, TriangleAlert } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { RevenueChart } from "@/components/dashboard/revenue-chart";
import { RefreshButton } from "@/components/dashboard/refresh-button";
import { formatCurrency } from "@/lib/utils";
import { requireSession } from "@/lib/auth/guard";
import { getUserOrganizations } from "@/lib/services/organizations";
import { getDashboardData } from "@/lib/services/dashboard";

export const dynamic = "force-dynamic";
const invoiceTone: Record<string, "neutral" | "success" | "warning" | "danger" | "brand"> = { paid: "success", issued: "brand", partially_paid: "warning", overdue: "danger", draft: "neutral" };
export default async function DashboardPage() {
  const session = await requireSession(); const organizations = await getUserOrganizations(session.user.id); const organization = organizations[0]; if (!organization) redirect("/onboarding");
  const dashboard = await getDashboardData(organization.id, "Asia/Kolkata"); const { metrics } = dashboard;
  const metricsCards = [
    { label: "Today’s sales", value: metrics.todaySales, icon: IndianRupee, note: "Issued invoices today", color: "text-indigo-500" },
    { label: "Today’s purchases", value: metrics.todayPurchases, icon: ShoppingBag, note: "Vendor bills today", color: "text-sky-500" },
    { label: "Today’s expenses", value: metrics.todayExpenses, icon: ReceiptText, note: "Recorded today", color: "text-amber-500" },
    { label: "Today’s profit", value: metrics.todayProfit, icon: TrendingUp, note: "Sales less purchases & expenses", color: metrics.todayProfit >= 0 ? "text-emerald-500" : "text-rose-500" },
  ];
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-[var(--brand)]">Executive overview</p><h1 className="mt-1 text-3xl font-black tracking-[-.05em]">Good morning, {session.user.name.split(" ")[0]}.</h1><p className="mt-2 text-sm text-[var(--muted)]">A live picture of {organization.name} as of now.</p></div><RefreshButton /></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metricsCards.map((metric) => { const Icon = metric.icon; return <Card key={metric.label} className="group"><CardContent><div className="flex items-start justify-between"><p className="text-sm font-semibold text-[var(--muted)]">{metric.label}</p><span className={`grid h-9 w-9 place-items-center rounded-xl bg-[var(--muted-surface)] ${metric.color}`}><Icon size={18} /></span></div><p className="mt-5 text-2xl font-black tracking-[-.045em]">{formatCurrency(metric.value, organization.currencyCode)}</p><p className="mt-2 text-xs text-[var(--muted)]">{metric.note}</p></CardContent></Card>; })}</section>
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1.65fr)_minmax(320px,.8fr)]"><Card><CardHeader><div><CardTitle>Revenue pulse</CardTitle><p className="mt-1 text-xs text-[var(--muted)]">Revenue compared with operating expenses</p></div><div className="flex items-center gap-3 text-xs font-semibold"><span className="flex items-center gap-1.5 text-[var(--muted)]"><i className="h-2 w-2 rounded-full bg-indigo-500" />Revenue</span><span className="flex items-center gap-1.5 text-[var(--muted)]"><i className="h-2 w-2 rounded-full bg-amber-500" />Expenses</span></div></CardHeader><CardContent className="pt-2"><RevenueChart data={dashboard.chart} /></CardContent></Card>
      <Card><CardHeader><div><CardTitle>Operational health</CardTitle><p className="mt-1 text-xs text-[var(--muted)]">Items to act on this week</p></div></CardHeader><CardContent className="space-y-3">{[{ label: "Outstanding receivables", value: formatCurrency(metrics.outstandingReceivables, organization.currencyCode), icon: ArrowDownRight, tone: "text-amber-500" }, { label: "Outstanding payables", value: formatCurrency(metrics.outstandingPayables, organization.currencyCode), icon: ArrowUpRight, tone: "text-rose-500" }, { label: "Inventory value", value: formatCurrency(metrics.inventoryValue, organization.currencyCode), icon: Boxes, tone: "text-indigo-500" }, { label: "Pending sales orders", value: String(metrics.pendingOrders), icon: PackageSearch, tone: "text-sky-500" }].map((item) => { const Icon = item.icon; return <div key={item.label} className="flex items-center gap-3 rounded-xl bg-[var(--muted-surface)]/65 p-3"><span className={`grid h-8 w-8 place-items-center rounded-lg bg-[var(--surface-solid)] ${item.tone}`}><Icon size={16} /></span><span className="min-w-0 flex-1 text-xs font-semibold text-[var(--muted)]">{item.label}</span><span className="text-sm font-black">{item.value}</span></div>; })}</CardContent></Card></section>
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1.4fr)_minmax(360px,1fr)]"><Card><CardHeader><div><CardTitle>Recent invoices</CardTitle><p className="mt-1 text-xs text-[var(--muted)]">Latest issued sales documents</p></div><Badge variant="brand">{dashboard.recentInvoices.length} recent</Badge></CardHeader><CardContent className="pt-3">{dashboard.recentInvoices.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs font-semibold text-[var(--muted)]"><tr className="border-b"><th className="pb-3">Invoice</th><th className="pb-3">Issued</th><th className="pb-3">Status</th><th className="pb-3 text-right">Total</th></tr></thead><tbody>{dashboard.recentInvoices.map((invoice) => <tr key={invoice.id} className="border-b last:border-0"><td className="py-3 font-bold">{invoice.invoiceNumber}</td><td className="py-3 text-xs text-[var(--muted)]">{new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short" }).format(new Date(invoice.issuedAt))}</td><td className="py-3"><Badge variant={invoiceTone[invoice.status] ?? "neutral"}>{invoice.status.replaceAll("_", " ")}</Badge></td><td className="py-3 text-right font-bold">{formatCurrency(invoice.total, organization.currencyCode)}</td></tr>)}</tbody></table></div> : <div className="grid min-h-48 place-items-center rounded-xl border border-dashed p-6 text-center"><div><CreditCard className="mx-auto text-[var(--muted)]" size={25} /><p className="mt-3 text-sm font-bold">No invoices yet</p><p className="mt-1 max-w-xs text-xs leading-5 text-[var(--muted)]">Issued invoices will appear here as your sales team begins billing.</p></div></div>}</CardContent></Card>
      <Card><CardHeader><div><CardTitle>Stock attention</CardTitle><p className="mt-1 text-xs text-[var(--muted)]">Products at or below reorder level</p></div><Badge variant={metrics.lowStock ? "warning" : "success"}>{metrics.lowStock} low</Badge></CardHeader><CardContent className="pt-3">{dashboard.lowStockItems.length ? <div className="space-y-2">{dashboard.lowStockItems.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl border p-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-amber-500/10 text-amber-600"><TriangleAlert size={16} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{item.name}</p><p className="mt-0.5 text-xs text-[var(--muted)]">{item.sku}</p></div><div className="text-right"><p className="text-sm font-black">{item.available}</p><p className="text-[10px] font-semibold uppercase tracking-wide text-[var(--muted)]">Reorder {item.reorderLevel}</p></div></div>)}</div> : <div className="grid min-h-48 place-items-center rounded-xl border border-dashed p-6 text-center"><div><Boxes className="mx-auto text-emerald-500" size={25} /><p className="mt-3 text-sm font-bold">Stock levels look healthy</p><p className="mt-1 max-w-xs text-xs leading-5 text-[var(--muted)]">Low-stock alerts will surface here when products and reorder levels are configured.</p></div></div>}</CardContent></Card></section>
  </div>;
}
