"use client";

import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowRight, Building2, Check, Factory, ShoppingBasket, Store, UtensilsCrossed, Wrench } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";

const businessTypes = [
  { value: "retail", label: "Retail", icon: Store }, { value: "wholesale", label: "Wholesale", icon: ShoppingBasket }, { value: "manufacturing", label: "Manufacturing", icon: Factory }, { value: "restaurant", label: "Food & beverage", icon: UtensilsCrossed }, { value: "services", label: "Professional services", icon: Wrench }, { value: "other", label: "Other business", icon: Building2 },
] as const;
const schema = z.object({ name: z.string().trim().min(2, "Business name must be at least 2 characters.").max(160), legalName: z.string().trim().max(200).optional(), businessType: z.enum(["retail", "wholesale", "manufacturing", "restaurant", "services", "other"]), currencyCode: z.string(), timezone: z.string() }); type Values = z.infer<typeof schema>;
export function WorkspaceOnboarding() { const router = useRouter(); const { register, handleSubmit, setValue, watch, formState: { errors, isSubmitting } } = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { businessType: "retail", currencyCode: "INR", timezone: "Asia/Kolkata" } }); const selected = watch("businessType"); const submit = async (values: Values) => { const response = await fetch("/api/organizations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const payload = await response.json() as { error?: string }; if (!response.ok) { toast.error(payload.error ?? "We couldn’t create the workspace."); return; } toast.success("Workspace created. Your owner role is ready."); router.replace("/dashboard"); router.refresh(); };
 return <div className="mx-auto max-w-3xl pb-10"><div className="mb-8 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-indigo-500/10 text-[var(--brand)]"><Building2 size={24} /></div><p className="mt-5 text-sm font-bold text-[var(--brand)]">First, your workspace</p><h1 className="mt-1 text-3xl font-black tracking-[-.05em] sm:text-4xl">Tell us about your business</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-[var(--muted)]">We’ll create an owner workspace with a fiscal year, main warehouse, permission matrix and reporting currency.</p></div><form noValidate onSubmit={handleSubmit(submit)} className="surface rounded-2xl p-5 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><div className="space-y-2 sm:col-span-2"><Label htmlFor="name">Business or workspace name</Label><Input id="name" placeholder="e.g. Horizon Traders" autoFocus aria-invalid={!!errors.name} {...register("name")} />{errors.name && <p className="text-xs font-medium text-[var(--danger)]">{errors.name.message}</p>}</div><div className="space-y-2 sm:col-span-2"><Label htmlFor="legalName">Legal name <span className="font-normal text-[var(--muted)]">(optional)</span></Label><Input id="legalName" placeholder="e.g. Horizon Traders Private Limited" {...register("legalName")} /></div></div><fieldset className="mt-7"><legend className="text-sm font-semibold">What best describes the business?</legend><div className="mt-3 grid gap-2 sm:grid-cols-2">{businessTypes.map((type) => { const Icon = type.icon; const isSelected = selected === type.value; return <button key={type.value} type="button" onClick={() => setValue("businessType", type.value, { shouldValidate: true })} className={cn("focus-ring flex items-center gap-3 rounded-xl border p-3 text-left transition-all", isSelected ? "border-indigo-500 bg-indigo-500/7 shadow-sm" : "hover:bg-[var(--muted-surface)]")}><span className={cn("grid h-9 w-9 place-items-center rounded-lg", isSelected ? "bg-indigo-500 text-white" : "bg-[var(--muted-surface)] text-[var(--muted)]")}><Icon size={17} /></span><span className="flex-1 text-sm font-bold">{type.label}</span>{isSelected && <Check size={17} className="text-[var(--brand)]" />}</button>; })}</div></fieldset><div className="mt-7 rounded-xl border bg-[var(--muted-surface)]/55 p-4"><p className="text-sm font-bold">What we’ll set up</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">INR reporting currency · Asia/Kolkata timezone · April–March fiscal year · Main Warehouse · Owner, manager, sales, inventory, finance and viewer roles.</p></div><div className="mt-7 flex justify-end"><Button size="lg" loading={isSubmitting}>Create workspace <ArrowRight size={17} /></Button></div></form></div>; }
